# Generated by Django 4.2.3 on 2023-07-28 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_server_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="categories",
            new_name="category",
        ),
    ]
