# Generated by Django 4.2.3 on 2023-08-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_server_banner_server_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
